version: '3'

volumes:
  data:

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"